language: python
python:
  - 3.6
  - 3.7
  - 3.8

# command to install dependencies
install:
  - "pip install -r tests/requirements.txt"
  # Download the latest version of the GAE Python SDK
  - "wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.30.zip -nv -O downloaded_appengine.zip"
  - "unzip -q downloaded_appengine.zip"
  # This is a quick hack, necessary to get fancy_urllib working,
  # by exposing the lib/fancy_urllib/fancy_urllib/ dirctory within for use by appengine.
  - "rm -rf google_appengine/lib/fancy_urllib/__init__.py"

# command to run tests
script: "pytest --cov wtforms_appengine tests"

after_success:
  - pip install coveralls
  - coveralls
