language: python
python:
  - 3.6
  - 3.7
  - 3.8

before_install:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv ${HOME}/venv
  - source ${HOME}/venv/bin/activate

  # Install CA certs, openssl to https downloads, python for gcloud sdk
  - sudo apt-get install make ca-certificates openssl python
  - sudo update-ca-certificates

  # Install Java
  - wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | apt-key add -
  - sudo apt-get update
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/
  - sudo apt-get -q update
  - sudo apt-get install -y adoptopenjdk-8-hotspot

  # Download the latest version of the GAE Python SDK
  - curl https://sdk.cloud.google.com > install.sh
  - bash install.sh --disable-prompts --install-dir=${HOME}
  - source ${HOME}/google-cloud-sdk/path.bash.inc
  - gcloud --quiet components update
  - gcloud components install cloud-datastore-emulator
  - gcloud components install beta
  - gcloud components install appctl
  - gcloud components install cloud-build-local
  - gcloud components install app-engine-python
  - gcloud components install app-engine-python-extras

# command to install dependencies
install:
  - "pip install -r tests/requirements.txt"
  # This is a quick hack, necessary to get fancy_urllib working,
  # by exposing the lib/fancy_urllib/fancy_urllib/ dirctory within for use by appengine.
  - "rm -rf google_appengine/lib/fancy_urllib/__init__.py"

# command to run tests
script: "pytest --cov wtforms_appengine tests"

after_success:
  - pip install coveralls
  - coveralls
